const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
const CHAT_SOCKET_CONNECTED = 'CHAT_SOCKET_CONNECTED';
const CHAT_SOCKET_DISCONNECTED = 'CHAT_SOCKET_DISCONNECTED';

export {SEND_MESSAGE_SUCCESS}
export {SEND_MESSAGE_FAIL}
export {CHAT_SOCKET_CONNECTED}
export {CHAT_SOCKET_DISCONNECTED}